### ISSUE TITLE
Add option to validate that document is correct JSON

### ISSUE THREAD

**Issue by rutsky** [nickcmaynard/jsonschemalint#3]
It's great that it is possible to enter documents in YAML format, but sometimes it's needed to validate document as JSON.
Valid YAML document can look like JSON, but actually be invalid JSON, e.g.

```
{
  "type": "object",
}
```

is not valid JSON due to excess comma.

**Comment by nickcmaynard** [comment]
@jhford Do you have any thoughts on this?

**Comment by nickcmaynard** [comment]
OK.  We're going to need to have YAML and JSON "modes" I think.

**Comment by nickcmaynard** [comment]
@rutsky Very happy to accept a PR.

**Comment by nickcmaynard** [comment]
Closing this - latest updates enable explicit selection of JSON/YAML, so this is "fixed".

**Comment by rutsky** [comment]
@nickcmaynard thanks!
