### ISSUE TITLE
json-loader missing from package.json

### ISSUE THREAD

**Issue by HotelDon** [nickcmaynard/jsonschemalint#35]
When cloning a fresh copy of the repo and running through the steps to start up the server, webpack fails to compile because it can't find json-loader - a quick search through package.json shows that it's missing from the list of dependencies. I'm guessing this was just an oversight, and adding it to dependencies or devDependencies via npm fixes the issue.

**Comment by nickcmaynard** [comment]
Please can you post recreation steps?  I can't recreate.  

json-loader is a dependency of webpack 2, but it's actually not needed any more, so I'll rip it out and replace with the native JSON loading.  But - I wonder what you're doing, and if this indicates I've documented something badly.

**Comment by HotelDon** [comment]
Well, cloning another copy and trying again resulted in no problems with webpack compiling - I've tried a couple different times running different commands with fresh clones and can't get it to happen again. Maybe it was just a fluke on my end? Since I can't seem to recreate it either I'll just close this issue.

**Comment by nickcmaynard** [comment]
Righto, thanks.  #36 removes the dependency entirely.
