### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by clenk** [nickcmaynard/jsonschemalint#38]
It would be helpful to be able to validate files on the command line, similar to JSONLint.

**Comment by HotelDon** [comment]
AJV, the validation library used by JsonSchemaLint for draft-04 and up, has a CLI package you can grab from NPM - you can more read about it [here](https://github.com/epoberezkin/ajv#command-line-interface).

**Comment by clenk** [comment]
Thank you!
