### ISSUE TITLE
Remove Google Analytics from master

### ISSUE THREAD

**Issue by asdorius** [nickcmaynard/jsonschemalint#46]
I cloned this project a few hours ago and was surprised to find this message in my Firefox console when I started hacking on it:

> The resource at "https://www.google-analytics.com/analytics.js" was blocked because tracking protection is enabled.

Without that feature turned on I would just have started to feed your GA-Tracker while working on internal company data. Every error I introduced would have sent details about my attempts to your GA feed.

**This is not good.**
I'm working in europe, so the current GDPR concerns are maybe driving me a little crazy here...

Now don't get me wrong: I have no trouble with Google Analytics on the hosted version at jsonschemalint.com . That's your site, you can do whatever you want with it.

----

My proposal is to move the GA code into its own branch or (better) into a fork of this project.
That way it stays in source control but isn't affecting other forks.

PS: Thanks for the work you put into this application, it's really helping me out right now.

**Comment by nickcmaynard** [comment]
GA is used for tracking pages, so I can understand traffic and usage, but doesn't get sent information about the content of the page.  You can check this yourself if you wish.

At present, I will not be removing this code from master, as I have automated deployment scripts that hang off this branch.

Please do fork this repo and remove the GA ID if you wish.
