### ISSUE TITLE
Package name (administrative question)

### ISSUE THREAD

**Issue by awwright** [nickcmaynard/jsonschemalint#48]
Hello,

As part of my contributions to JSON Schema, I'm looking at creating a library that does linting of JSON Schemas (but think a utility like eslint or similar linters), with features like reporting unknown keywords, redundant keywords (e.g. supplying "type" and "enum" at the same time), and such.

I thought of using the name "json-schema-lint" and I noticed your package.json uses this. While it doesn't seem to have been published to the npm repository, I wanted to ask if it's alright if I publish a library under this name anyways.

You might be interested in incorporating some of this functionality in, and I like what you've got, so I'll look at sending pull requests as appropriate too.

Thanks!

**Comment by nickcmaynard** [comment]
Hi!

How about we scope our package names?  

I’ll drop in something like “@nickcmaynard/jsonschemint.com”, and you could use “@awwright/jsonschemalint” or some such.

This way, there’s no confusion.

**Comment by awwright** [comment]
I can try that for now and see if that works.

I intend for this to be a generally available package in the same manner that eslint is, though. Is a scoped package something you'd be able to use yourself?

Also I like the idea of naming an application after the domain name it's hosted at.
