### ISSUE TITLE
Add the ability to link to results

### ISSUE THREAD

**Issue by nubs** [nickcmaynard/jsonschemalint#7]
It would be nice if there was a way to link to a specific result.  The easiest way would probably be to accept query parameters that define the schema and json being validated.

This would help a lot with trying to share a failing JSON document with others so they can collaboratively help fix the errors.

Another potential use would be to only prefill the schema.  Being able to link to a schema validator for a particular schema would be useful from a documentation standpoint.  Instead of just linking to the schema itself, projects could link to the validator and users could supply their JSON to make sure it validates with one fewer step.

**Comment by nickcmaynard** [comment]
Sounds like a great idea.  I see two features here:
1. Prefill schema (and documents) from somewhere.
1. Save everything for further reuse/forking.

Prefilling we can do with simple query params:
`/draft4/?schema=https%3A%2F%2Fraw.githubusercontent.com%2Fnickcmaynard%2Fjsonschemalint%2Fmaster%2Fdraft4%2Fsamples%2Fvalid.schema.json&document=https%3A%2F%2Fraw.githubusercontent.com%2Fnickcmaynard%2Fjsonschemalint%2Fmaster%2Fdraft4%2Fsamples%2Fvalid.document.json`

With saving, the issue will be storage - right now, the app is completely stateless.  I can't think of a way to get a URL link to embed enough information, so this would have to live in a Database.  And now complexity goes up.  Any bright ideas?

**Comment by nubs** [comment]
Yeah, saving is definitely harder of a problem.  Adding the schema as a link in the query parameter makes for the quickest improvement, but saving it somewhere would be even more useful.

localStorage could be used for someone to revisit their previous schemas but that wouldn't solve the issue of sharing it with others.

**Comment by nickcmaynard** [comment]
Potential thought - we could store it in anonymous github.com gists...

**Comment by nickcmaynard** [comment]
Done.

**Comment by nubs** [comment]
Thanks so much for your work on this!  That's awesome :)

**Comment by nickcmaynard** [comment]
FYI the code here is a bit gnarly - the alert() code for success/failure particularly is a quick hack.  If you have time to put in some better alert/dialog/toaster/whatever logic, I'd gladly accept a PR.
